version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    command: postgres -c log_statement=all
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
      - ./.postgres-run:/run/postgresql

  pgadmin:
    profiles: ["tools"]
    image: dpage/pgadmin4
    ports:
      - "9201:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@localhost.localdomain
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_DISABLE_POSTFIX: "true"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - ./.pgadmin-data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
      - ./docker/pgadmin/home:/home
      - ./.postgres-run:/run/postgresql
